# Generated by Django 5.2.3 on 2025-06-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('media_count', models.IntegerField(default=0)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('from_username', models.CharField(max_length=200)),
                ('from_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL_ALBUM', 'Carousel'), ('STORY', 'Story'), ('REEL', 'Reel')], default='IMAGE', max_length=20)),
                ('media_url', models.URLField(blank=True)),
                ('permalink', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_time', models.DateTimeField()),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('from_username', models.CharField(max_length=200)),
                ('from_id', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('like_count', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.instagrampost')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=100, unique=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL_ALBUM', 'Carousel'), ('STORY', 'Story'), ('REEL', 'Reel')], default='IMAGE', max_length=20)),
                ('media_url', models.URLField(blank=True)),
                ('created_time', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.instagramaccount')),
            ],
        ),
    ]
